[package]
name = "logging"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "logging"
path = "src/lib.rs"


[dependencies]
chrono = "0.4.34"
colored = "2.1.0"
env_logger = "0.11.2"
log = "0.4.21"
